### ISSUE TITLE
[Feature Request] Create questionnaire for after workshop

### ISSUE THREAD

**Issue by bartvanb** [vantage6/vantage6-workshop#107]
**Problem description**
After the workshop we should get feedback from participants what they liked and didn't like, so we can improve future iterations / an online version

**Desired solution**
Create this questionnaire **before** the workshop so that we can send it the day after.

**Comment by frankcorneliusmartin** [comment]
@dsmits template (pre and post workshop survey)

**Comment by bartvanb** [comment]
Sent by @dsmits:
pre-workshop: https://carpentries.github.io/assessment-archives/pre-workshop/pre-workshop.html
post-workshop: https://carpentries.github.io/assessment-archives/post-workshop/post-workshop.html

My feedback on this:

Pre-workshop survey
- Looks fine to me, maybe a bit on the long side (some things like demographics are not very relevant to know I think)
- Why do we need the identifier for these people? To compare post- and pre-workshop surveys? Maybe we can say that that is the reason we're asking it

Post-workshop:
- I feel inclined to ask per episode if 1) they thought it was relevant, 2) how well it was taught and 3) suggestions to improve it. I think that input would be important for any subsequent workshops we might teach
- The questions about writing scripts, whether they are comfortable using R or Python or so, are not very relevant to ask twice as I don't think this workshop changes those

**Comment by frankcorneliusmartin** [comment]
https://forms.office.com/Pages/DesignPageV2.aspx?subpage=design&FormId=zOo6qgdjskKsBXh91cMldOMN8IMKMnZFgh-jld93H45UMVlXM0wwT05YRkw2Rk9DMVVVMlE3Vkk3MC4u&Token=1e839eed3b9f4c41a2624175a0ae3f14
