### ISSUE TITLE
[Change Request] Introduction missing in workshop agenda

### ISSUE THREAD

**Issue by bartvanb** [vantage6/vantage6-workshop#108]
**Description**
In the schedule on https://workshop2024.vantage6.ai/, there is no time planned for an introduction.

**Suggestion**

9:30-10:00 coffee/registration
10:00-10:15 welcome/intro

everything else then shifts 15min so that we end at 17:00 rather than 16:45

- [x] Do above
- [x] Think if necessary in other places
- [ ] ~~Other question, should we provide some kind of name tags? Maybe just stickers on which people can write their name~~ (handled in other issue)

**Comment by dsmits** [comment]
Name tags sounds good to me

**Comment by dsmits** [comment]
Don't think the schedule needs to be changed in other places

**Comment by dsmits** [comment]
Another thing to fix: no abbreviations in agenda. Just write out PET fully as privacy enhancing technology

**Comment by frankcorneliusmartin** [comment]
related: #86
