### ISSUE TITLE
[Change Request] chapter 4 rehearsal issues

### ISSUE THREAD

**Issue by CunliangGeng** [vantage6/vantage6-workshop#110]
- [x] Very nice  that you started with a recap :+1:
- [x] Too much time spent on exact permissions and roles, etc
- [x] When you skip 'Encrypted' maybe mention where people can find more information about this, now it looks like a very important thing that is skipped
  - Add doc link 
- [x] Tell that the search bar is case sensitive
- [x] When you show things on screen, it would be nice if you login with a user that has the same permissions as the participants. Now you were logging in as root user, and the differences can be confusing

**Comment by CunliangGeng** [comment]
@bartvanb Could you create two more accounts for me with role Researcher and Collaboration Admin? Please do not change my root account.

**Comment by bartvanb** [comment]
@CunliangGeng could you create them yourself for the time being via the UI? You can then use those to test your lessons. 
Note that there already is a "workshop admin" role now (see https://github.com/vantage6/vantage6-workshop/pull/138), so you should assign that to your test admin user. 
Please use different usernames as `cgeng` and `cgeng_admin` as the script we will run for the real workshop would then fail on unique constraints

**Comment by CunliangGeng** [comment]
@bartvanb Thanks Bart, I'll create them.
