### ISSUE TITLE
[Feature Request] Write setup

### ISSUE THREAD

**Issue by dsmits** [vantage6/vantage6-workshop#22]
- installing docker (see docker lesson setup https://carpentries-incubator.github.io/docker-introduction/setup.html)
- installing conda
- installing vantage6, vantage6-client, vantage6-algorithm-tools

- mention the requirements described in chapter 6

**Comment by dsmits** [comment]
Check chapter 6

**Comment by bartvanb** [comment]
Also: 
- jupyter notebook installation (for python client work)
