### ISSUE TITLE
[Overview] Infrastructure

### ISSUE THREAD

**Issue by bartvanb** [vantage6/vantage6-workshop#30]
**Problem description**
In the workshop, participants should be able to login to their own vantage6 environment with the UI and do stuff.

**Desired solution**

For creating analyses:
- [x] One node+organization per participant, which are grouped in collaborations (~4-5 participants per collaboration)
  - [x] Each participant gets `researcher` role
  - [x] Generate dataset for each node
  - [x] ~~Hand out datasets to the participants (on paper)~~ -> Done in #139 
  - [x] Hand out passwords
  - [x] There should be a few extra organizations in the collaboration whose nodes are not online. Then create a study without these dummy orgs to do the analyses on.
  - [x] These collaborations should have access to the community algorithm store, or if challenges require it, yet another algorithm store
- [x] One server with high load
  - [x] ~~scale to 4 instances before workshop (currently at 2)~~ -> Ignoring this here, discussed in #137 

For administration exercises:
- [x] Each participant gets 2 dummy collaborations with `collaboration admin` role.
  - [x] Depends on the assignments

Other:
- [x] ~~create project in `harbor2.vantage6.ai/workshop` where they can push algorithm images (for algorithm development)~~
  - [x] OR should they create account on Docker hub? -> Yes but we let them do it during the workshop

**Additional context**
https://github.com/vantage6/vantage6/issues/1314 would make it easier for them to run complete `v6 dev` networks

**Comment by hcadavid** [comment]
@bartvanb the challenges on chapter no. 3 (and eventually on chapter 5) are based on [a scenario with four organizations](https://github.com/vantage6/vantage6-workshop/blob/628fed123f9a56f0b25c670c6daefac3da883b36/episodes/chapter3.md?plain=1#L83) and two collaborations (basically to make them explore multiple collaboration configurations with different statuses through the UI). Now I see that four may be too much :), but could we have at least three? (so there are still two collaborations for them to explore). With only one or two nodes these challenges would need to be redefined. Three, on the other hand, would require only a minor update. 

For the same exercise, four users are considered (one admin and one researcher for each collaboration).

**Comment by bartvanb** [comment]
@hcadavid good that you spotted this! The most important for me is that we limit the number of nodes we need to run per participant, as that requires most computational resources. The registration of multiple collaborations/organizations etc at the server is peanuts, it's something we will script anyway and then it doesn't really matter how many loops we run.

Am I understanding correctly that we need 3 nodes divided over 2 collaborations? Is there then one collaboration with 2 nodes and the other one with 1?

**Comment by hcadavid** [comment]
@bartvanb I'd describe it as three organizations (OrgA, OrbB, OrgC) divided over two collaborations (ColX, ColY). In other words two organizations with one node each one: (OrgA-ColX, OrgB-ColY), and the third organization with two nodes -one for each collaboration- (OrgC-ColX, OrgC-Coly) - so four nodes in total. 

As I mentioned, if having (4*#participants) nodes is too computationally expensive, depending on the maximum number of nodes per participant (two, or three?) we may need to change the context given on EP3 (which illustrates, among others, how the same organization can be part of multiple collaborations) and also some of the challenges for EP3 and EP5.

**Comment by bartvanb** [comment]
OK I updated the TODO list above, please check if you agree!

**Comment by hcadavid** [comment]
Looks good to me! I'll add an issue to update EP3 scenario with three orgs.

**Comment by bartvanb** [comment]
After our discussion today, I updated the checklist again

**Comment by hcadavid** [comment]
Hi @bartvanb and @frankcorneliusmartin 

To be sure I understand the idea correctly, I made a quick diagram to double-check the nodes/collabs configurations with you (O1, O2... O35, are the organizations created for each participant). The diagram on the right would be the one closest to the configuration we just discussed, right?

Looking at Episode 3, I remembered that algorithms like 'average' (if I'm not mistaken) only works in a collaboration where all the nodes are 'active', and that this is why this exercise requires two collaborations: one with all the nodes online (for participants to run an algorithm on), and another with one or more 'inactive' nodes (for participants to see alternative statuses of a collaboration). 

Given this, wouldn't the configuration described at the left be also an option? (Two collaborations per group, one of them with an extra 'offline' node organization). This would require twice the number of nodes, but the ~35 extra ones would never be used.

![image](https://github.com/user-attachments/assets/03b6e475-f083-4a18-b1a2-88720a13ce5e)

Please let me know what you think, e.g., if I'm missing something from our discussion about this matter.

[workshop-v6-setup.drawio.zip](https://github.com/user-attachments/files/16247753/workshop-v6-setup.drawio.zip)

**Comment by bartvanb** [comment]
Hi @hcadavid , I agree that the diagram on the right is what we discussed. Indeed, the left diagram would be a good solution to the issue of 1 node being offline, but there is a different way to solve this: the 'study' concept.

The idea of a study is that you can define a subset of the collaboration to do certain analyses together. So in the diagram on the right, you would create one study that contains all organizations *except* the one that is offline. Then, when you select that study for the tasks you create, it will not be sent to the organization that is offline.

**Comment by CunliangGeng** [comment]
@bartvanb Thanks, it's a good idea to use the downloaded API keys. I'll update ch4 and ch6 to make sure they save the API key properly.
