### ISSUE TITLE
Arrange dinner reservation

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6-workshop#51]
Sacha will help us arrange the lunches (#52) and dinner.

## Requirements

- Including drink 55-60 EUR per person, 6-40 people.
- Starts from 18:30

* Allergies
* Vegan / Vegetarian ? 
* Gluten free

## Restaurant

Umami (sushi, grilled, wok, fried, etc,  all you can eat) https://umamiutrecht.nl/menulijst/

---

**Catering service**
https://hummusandhabibis.com/

**Comment by frankcorneliusmartin** [comment]
* We got some critical notes that not everybody likes sushi

**Comment by CunliangGeng** [comment]
> * We got some critical notes that not everybody likes sushi

There are many other options, e.g. [grilled, wok, fired](https://umamiutrecht.nl/menulijst/). It should be fine, I guess.

**Comment by CunliangGeng** [comment]
Dinner booking is confirmed for 14 persons on October 16th 18:30. I will sign the bill.
