### ISSUE TITLE
Arrange lunch

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6-workshop#52]
Sacha will help us arrange the lunches and dinner (#51).

## Requirements
- budget per person (15-20 euro per person per day, 6-40 people)
- Deliver to Beatrixgebouw Jaarbeurs, HI-FIVE: 5th floor, Jaarbeursplein 6, 3521 AL Utrecht

- Don't make people hangry

## Restaurant

---

**Catering service**
https://hummusandhabibis.com/

**Comment by CunliangGeng** [comment]
Lunch will be delivered from Lunchtijd.nl for 16 & 17 Oct 11:45.
