### ISSUE TITLE
Mail participants with latest info (two weeks before workshop)

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6-workshop#54]

**Comment by bartvanb** [comment]
Dear vantage6 workshop participant,

The vantage6 workshop is approaching and we are excited to seeing all of you there on October 16 & 17. In this email, we are providing you with some logistical details.

The workshop starts on Wednesday the 16th at 10:00 at HI-Five (5th floor), Jaarbeursplein 6, Utrecht, the Netherlands. You can arrive and register from 9:30 onwards. For how to get there, see the end of this email, and for more details, see the workshop website at https://workshop2024.vantage6.ai/.

We ask everyone to bring a laptop to work on exercises during the workshop. If you only participate the first day, you do not need to install anything as we will not run vantage6 locally on your laptop. However, for most of you that participate both days, we firmly ask you to install the requirements to run vantage6 on your laptop, as detailed in https://workshop.vantage6.ai/#software-setup. By doing this in advance, we can teach you more about vantage6 during the workshop days, and if necessary, we will be able to help you out if you run into trouble so you can make of this workshop. Please briefly join our setup session on Wednesday 9th of October from 9-10 to let us know that your installation was successful. If necessary, we can also help you out during that time slot.

Lunch is included on both days of the workshop. For those of you that have registered for the workshop dinner, this will take place at 18:30 at Umami Asian cuisine, Oudegracht 74, Utrecht (https://umamiutrecht.nl/).

See you soon!

Best regards,
The vantage6 workshop Team

How to get to the workshop:
Address: HI-Five, 5th floor Beatrixgebouw, Jaarbeursplein 6, 3521 AL Utrecht, The Netherlands

From the Utrecht Central Station follow the signs ’Jaarbeursplein’. Once you reached the square from the station, you will find the Beatrixgebouw on your left. Enter the building and take the elevator to the 5th floor (HI-Five office).
Image

**Comment by frankcorneliusmartin** [comment]
Dont forget to add the Teams link for the setup sessions.

**Comment by frankcorneliusmartin** [comment]
Email has been send out! 🎉
