### ISSUE TITLE
[Change Request] Chapter 3 diagram not easy to read

### ISSUE THREAD

**Issue by dsmits** [vantage6/vantage6-workshop#68]
[The diagram with the relationships between entities](https://workshop.vantage6.ai/chap3_run_analysis_ui.html#vantage6-user-interface-basics) might make sense from a technical perspective, but it is not super easy to read.

I think it would help if we would have different icons for the different types of entities.

Also I'm not sure if we should phrase things as a "n-1" relationship for the GUI clicker audience. Now they have to learn both the concept of vantage *and* the concept of types of relationships

**Comment by hcadavid** [comment]
Addressed on PR https://github.com/vantage6/vantage6-workshop/pull/82
The ER diagrams were replaced with more user-friendly ones.
