### ISSUE TITLE
[Change Request] Chapter 5: Use concrete resource instead of placeholder <resource>

### ISSUE THREAD

**Issue by dsmits** [vantage6/vantage6-workshop#69]
In [Using the client](https://workshop.vantage6.ai/chap5_python_client.html#using-the-client) I think it is better to use a concrete resource instead of a placeholder \<resource\> .

When concretely using something like `client.organization.list()` participants can actually execute it and I think that is more powerful as a learning experience.

**Comment by frankcorneliusmartin** [comment]
This was already done. Thanks.
