### ISSUE TITLE
[Change Request] Chapter 7: create a personalized boilerplate is more instructions than an exercise

### ISSUE THREAD

**Issue by dsmits** [vantage6/vantage6-workshop#72]
The [Create a personalized boilerplate challenge](https://workshop.vantage6.ai/chap7_algo_dev.html#challenge-1-create-a-personalized-boilerplate) is not really an exercise, but more like instructions.

**Comment by bartvanb** [comment]
@dsmits I agree but we do need the participants to do this. Is there a good alternative to challenge, like 'task' or 'do it yourself'?

**Comment by dsmits** [comment]
This is gonna be some command line things right? You can just type out the commands and what you fill in in the prompts. THen maybe after that you can do an exercise to test if the participants understand what they did.
