### ISSUE TITLE
[Change Request] Chapter 1: refine explanation on differential privacy

### ISSUE THREAD

**Issue by dsmits** [vantage6/vantage6-workshop#77]
There seems to be different ways to add when using differential privacy.

Currently we are describing differential privacy techniques as replacing a subset of records with noise.

There seem to be different methods as well, where the noise is added to the raw values (instead of replacement).

Let's figure out a little bit more about the landscape of differential privacy and adapt the text.

Sources:
- https://desfontain.es/blog/differential-privacy-in-practice.html
- https://www.youtube.com/watch?v=mO0NmkVGapM

**Comment by dsmits** [comment]
This video was quite helpful on listing different techniques: https://www.youtube.com/watch?v=Quzx_QaARAE&t=0s

**Comment by bartvanb** [comment]
Maybe you can mention the links in the lesson for students interested to know more?

**Comment by dsmits** [comment]
@bartvanb I will open a separate issue for that because I think the list of links has to be more complete than just differential privacy: #88
