### ISSUE TITLE
[Change Request] Making the comments on the 'average' code more precise

### ISSUE THREAD

**Issue by hcadavid** [vantage6/vantage6-workshop#96]
Chapter 3 involves the analysis of the 'average' algorithm by the participants. However, the way it is documented may lead to confusion, as it is described in terms of collaborations, and the exercise is based on studies. Would it be possible to update the comments on this [module]( https://github.com/IKNL/v6-average-py/blob/master/v6-average-py/__init__.py) so it is more precise about how it would also work with studies? I'm not doing this through a PR as I don't have access to the IKNL Github organization.

E.g:

_'First we collect the parties that participate in the collaboration.'_ -> 
_'First we collect the parties that participate in the collaboration or in the study (depending on which one is being used as the target).'_

**Comment by bartvanb** [comment]
Fixed this in https://github.com/IKNL/v6-average-py/pull/5 - I updated the entire docstring as more things were outdated
